# Generated by Django 5.0.6 on 2025-09-24 12:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("due_at", models.DateTimeField(verbose_name="마감일시")),
                (
                    "max_score",
                    models.PositiveIntegerField(default=100, verbose_name="배점"),
                ),
                (
                    "late_policy",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="지연 정책"
                    ),
                ),
                (
                    "file_rules",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="파일 규칙"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자(교수)",
                    ),
                ),
            ],
            options={
                "verbose_name": "과제",
                "verbose_name_plural": "과제",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_id",
                    models.CharField(max_length=20, unique=True, verbose_name="학번"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "학생 프로필",
                "verbose_name_plural": "학생 프로필",
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_submitted", "미제출"),
                            ("late", "지연제출"),
                            ("submitted", "제출됨"),
                            ("graded", "채점완료"),
                        ],
                        default="not_submitted",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="제출 메모")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="제출일시"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submit.assignment",
                        verbose_name="과제",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="학생",
                    ),
                ),
            ],
            options={
                "verbose_name": "제출",
                "verbose_name_plural": "제출",
            },
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(verbose_name="점수")),
                ("feedback_text", models.TextField(blank=True, verbose_name="피드백")),
                (
                    "graded_at",
                    models.DateTimeField(auto_now=True, verbose_name="채점일시"),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="채점자",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submit.submission",
                        verbose_name="제출",
                    ),
                ),
            ],
            options={
                "verbose_name": "성적",
                "verbose_name_plural": "성적",
            },
        ),
        migrations.CreateModel(
            name="SubmissionFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="submissions/", verbose_name="파일"),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="버전"),
                ),
                (
                    "size",
                    models.PositiveIntegerField(default=0, verbose_name="크기(Byte)"),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="submit.submission",
                        verbose_name="제출",
                    ),
                ),
            ],
            options={
                "verbose_name": "제출 파일",
                "verbose_name_plural": "제출 파일",
                "ordering": ["submission_id", "version"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="팀명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "join_code",
                    models.CharField(
                        editable=False, max_length=6, unique=True, verbose_name="팀코드"
                    ),
                ),
                (
                    "join_code_generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="팀코드 발급일시"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_teams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자(교수)",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀",
                "verbose_name_plural": "팀",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="assignment",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="submit.team",
                verbose_name="팀",
            ),
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기"),
                            ("APPROVED", "승인"),
                            ("REJECTED", "거절"),
                            ("LEFT", "탈퇴"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="상태",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="member",
                        max_length=20,
                        verbose_name="팀 역할",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="요청일시"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="결정일시"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="최종참가일시"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_team_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="결정자(교수)",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="학생",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="submit.team",
                        verbose_name="팀",
                    ),
                ),
            ],
            options={
                "verbose_name": "팀 멤버십",
                "verbose_name_plural": "팀 멤버십",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30, verbose_name="유형")),
                (
                    "payload",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="추가 데이터"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="읽은 시각"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="대상 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림",
                "indexes": [
                    models.Index(
                        fields=["user", "type"], name="submit_noti_user_id_853ea3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="submit_noti_created_943737_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="submission",
            constraint=models.UniqueConstraint(
                fields=("assignment", "student"), name="uq_assignment_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="uq_team_owner_name"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "status"], name="submit_team_team_id_ea86aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["student", "status"], name="submit_team_student_f35bab_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "student"), name="uq_team_student"
            ),
        ),
    ]
