# Generated by Django 5.0.6 on 2025-09-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="is_closed",
            field=models.BooleanField(default=False, verbose_name="마감됨"),
        ),
    ]
