# Generated by Django 5.0.6 on 2025-09-24 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0002_course_assignment_notification_submission_grade_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"verbose_name": "과제", "verbose_name_plural": "과제"},
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "과목", "verbose_name_plural": "과목"},
        ),
        migrations.AlterModelOptions(
            name="enrollment",
            options={"verbose_name": "수강 등록", "verbose_name_plural": "수강 등록"},
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"verbose_name": "성적", "verbose_name_plural": "성적"},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "알림", "verbose_name_plural": "알림"},
        ),
        migrations.AlterModelOptions(
            name="studentprofile",
            options={
                "verbose_name": "학생 프로필",
                "verbose_name_plural": "학생 프로필",
            },
        ),
        migrations.AlterModelOptions(
            name="submission",
            options={"verbose_name": "제출", "verbose_name_plural": "제출"},
        ),
        migrations.AlterModelOptions(
            name="submissionfile",
            options={"verbose_name": "제출 파일", "verbose_name_plural": "제출 파일"},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="submit.course",
                verbose_name="과목",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="description",
            field=models.TextField(blank=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="due_at",
            field=models.DateTimeField(verbose_name="마감일시"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="file_rules",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="파일 규칙"
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="late_policy",
            field=models.CharField(blank=True, max_length=50, verbose_name="지연 정책"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="max_score",
            field=models.PositiveIntegerField(default=100, verbose_name="배점"),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=120, verbose_name="제목"),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, unique=True, verbose_name="과목코드"),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teaching_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="담당교원",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100, verbose_name="과목명"),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="submit.course",
                verbose_name="과목",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="role_in_course",
            field=models.CharField(
                choices=[("student", "학생"), ("ta", "조교")],
                default="student",
                max_length=10,
                verbose_name="역할",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="feedback_text",
            field=models.TextField(blank=True, verbose_name="피드백"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="graded_at",
            field=models.DateTimeField(auto_now=True, verbose_name="채점일시"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="채점자",
            ),
        ),
        migrations.AlterField(
            model_name="grade",
            name="score",
            field=models.PositiveIntegerField(verbose_name="점수"),
        ),
        migrations.AlterField(
            model_name="grade",
            name="submission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="submit.submission",
                verbose_name="제출",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="payload",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="추가 데이터"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="읽은 시각"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(max_length=30, verbose_name="유형"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="대상 사용자",
            ),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="student_id",
            field=models.CharField(max_length=20, unique=True, verbose_name="학번"),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="사용자",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="submit.assignment",
                verbose_name="과제",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="comment",
            field=models.TextField(blank=True, verbose_name="제출 메모"),
        ),
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "미제출"),
                    ("late", "지연제출"),
                    ("submitted", "제출됨"),
                    ("graded", "채점완료"),
                ],
                default="not_submitted",
                max_length=20,
                verbose_name="상태",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="학생",
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="제출일시"),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="file",
            field=models.FileField(upload_to="submissions/", verbose_name="파일"),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="size",
            field=models.PositiveIntegerField(default=0, verbose_name="크기(Byte)"),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="submit.submission",
                verbose_name="제출",
            ),
        ),
        migrations.AlterField(
            model_name="submissionfile",
            name="version",
            field=models.PositiveIntegerField(default=1, verbose_name="버전"),
        ),
    ]
