# Generated by Django 5.0.6 on 2025-09-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0002_assignment_is_closed"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_covers/",
                verbose_name="대표 이미지",
            ),
        ),
    ]
